apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-auth
  namespace: argocd
spec:
  project: auth
  source:
    repoURL: https://github.com/abayleypublic/apps
    targetRevision: HEAD
    path: deploy/system/auth/stg
    kustomize:
      images:
        - quay.io/oauth2-proxy/oauth2-proxy:v7.13.0-alpine
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: stg-auth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true
