apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon
  namespace: argocd
spec:
  project: system
  sources:
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/tetragon/chart
      helm:
        valueFiles:
        - ../values.yaml
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/tetragon/base
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true
    
