apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
spec:
  project: temporal
  source:
    chart: Chart.yaml
    repoURL: https://github.com/abayleypublic/apps
    targetRevision: HEAD
    path: apps/temporal/chart
    helm:
      releaseName: temporal
      valueFiles:
        - apps/temporal/values.yaml
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: temporal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
