apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-account
  namespace: argocd
spec:
  project: account
  source:
    repoURL: https://github.com/abayleypublic/account
    targetRevision: v0.1.0
    path: deploy/overlays/stg
    kustomize:
      images:
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/account_backend:v0.1.0
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/account_ui:v0.1.0
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: stg-account
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true
