apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator-helm
  namespace: argocd
spec:
  project: system
  sources:
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/otel/operator-helm/chart
      helm:
        valueFiles:
          - ../values.yaml
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/otel/ebpf
      kustomize:
        images:
          - otel/ebpf-instrument:v0.4.1
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/otel/collector
      kustomize:
        images:
          - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.142.0
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true
