apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roam
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abayleypublic/activity_tracker_api
    targetRevision: v0.0.18
    path: deploy/overlays/prod
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: roam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
