apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roam
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abayleypublic/activity_tracker_api
    targetRevision: HEAD
    path: deploy/overlays/prod
    kustomize:
      images:
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/activity_tracker_api:v0.2.1
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: roam
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
