apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-roam
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abayleypublic/activity_tracker_charity
    # targetRevision: v1.1.1
    targetRevision: HEAD
    path: deploy/overlays/stg
    kustomize:
      images:
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/activity_tracker_charity:v1.1.1
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: stg-roam
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
