apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-queue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abayleypublic/queue
    targetRevision: test
    path: deploy/overlays/stg
    kustomize:
      images:
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue:test
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: stg-queue
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
