apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-helm
  namespace: argocd
spec:
  project: system
  sources:
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/temporal/chart
      helm:
        valueFiles:
          - ../values.yaml
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/temporal/base
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: temporal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true