apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-helm
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://github.com/abayleypublic/apps
    targetRevision: HEAD
    path: deploy/system/otel/operator-helm/chart
    helm:
      valueFiles:
        - ../values.yaml
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
