apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-helm
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://github.com/abayleypublic/apps
    targetRevision: HEAD
    path: apps/temporal/chart
    helm:
      valueFiles:
        - ../values.yaml
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: temporal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
