apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://github.com/abayleypublic/apps
    targetRevision: HEAD
    path: deploy/system/otel/collector
    kustomize:
      images:
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.142.0
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
