apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-queue
  namespace: argocd
spec:
  project: queue
  source:
    repoURL: https://github.com/abayleypublic/queue
    targetRevision: HEAD
    path: deploy/overlays/stg
    kustomize:
      images:
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend:v0.1.2
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_gateway:v0.1.1
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_mcp:v0.1.0
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_service:v0.1.0
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_ui:v0.1.0
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: stg-queue
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
