apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-queue
  namespace: argocd
spec:
  project: queue
  source:
    repoURL: https://github.com/abayleypublic/queue
    targetRevision: HEAD
    path: deploy/overlays/stg
    kustomize:
      images:
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend:test
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_gateway:test-6
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_mcp:test
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_service:test-3
        - europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_ui:test-4
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: stg-queue
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
