apiVersion: v1
kind: ConfigMap
metadata:
  name: obi-config
data:
  obi-config.yml: |
    network:
      enable: true
    attributes:
      kubernetes:
        enable: true
    routes:
      unmatched: heuristic
    trace_printer: text
    ebpf:
      context_propagation: all
      traffic_control_backend: tcx
      disable_blackbox_cp: true
      track_request_headers: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obi
  labels:
    app: obi
spec:
  selector:
    matchLabels:
      app: obi
  template:
    metadata:
      labels:
        app: obi
    spec:
      hostPID: true
      serviceAccountName: obi
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: autoinstrument
          resources:
            limits:
              memory: 120Mi
          image: otel/ebpf-instrument
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://otel-collector:4318'
            - name: OTEL_EBPF_KUBE_METADATA_ENABLE
              value: "autodetect"
            - name: OTEL_EBPF_METRIC_FEATURES
              value: 'application'
            - name: OTEL_EBPF_CONFIG_PATH
              value: '/config/obi-config.yml'
          securityContext:
            runAsUser: 0
            readOnlyRootFilesystem: true
            capabilities:
              add:
                - BPF
                - SYS_PTRACE
                - NET_RAW
                - CHECKPOINT_RESTORE
                - DAC_READ_SEARCH
                - PERFMON
                - NET_ADMIN
                - SYS_ADMIN
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup 
            - mountPath: /config
              name: obi-config
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - name: obi-config
          configMap:
            name: obi-config
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
          
