apiVersion: v1
kind: ConfigMap
metadata:
  name: obi-config
data:
  obi-config.yml: |
    network:
      enable: true
      source: tc
    attributes:
      kubernetes:
        enable: true
    routes:
      unmatched: heuristic
    trace_printer: text
    ebpf:
      context_propagation: all
      traffic_control_backend: tcx
      disable_blackbox_cp: false
      track_request_headers: true
    discovery:
      min_process_age: 5s
      # exclude_otel_instrumented_services: true
      instrument:
        - k8s_pod_annotations:
            ebpf.instrument: "true"
        - k8s_pod_annotations:
            ebpf.instrument: "python"
          exe_path: "*/python3.*"
        # - k8s_namespace: temporal
        - k8s_namespace: "envoy-gateway-system"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obi
  labels:
    app: obi
spec:
  selector:
    matchLabels:
      app: obi
  template:
    metadata:
      labels:
        app: obi
    spec:
      hostPID: true
      serviceAccountName: obi
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: autoinstrument
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          image: otel/ebpf-instrument
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://otel-collector:4317'
            - name: OTEL_EBPF_KUBE_METADATA_ENABLE
              value: "autodetect"
            - name: OTEL_EBPF_CONFIG_PATH
              value: '/config/obi-config.yml'
          securityContext:
            runAsUser: 0
            readOnlyRootFilesystem: true
            capabilities:
              add:
                - BPF
                - SYS_PTRACE
                - NET_RAW
                - CHECKPOINT_RESTORE
                - DAC_READ_SEARCH
                - PERFMON
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_RESOURCE
          volumeMounts:
            - name: obi-config
              mountPath: /config
            - name: cgroup
              mountPath: /sys/fs/cgroup 
            - name: security
              mountPath: /sys/kernel/security
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - name: obi-config
          configMap:
            name: obi-config
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: security
          hostPath:
            path: /sys/kernel/security
