apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - roles.yaml
  - daemonset.yaml

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:
  - name: obi-config
    files:
      - obi-config.yaml=config.yaml