apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://github.com/abayleypublic/apps
    targetRevision: HEAD
    path: apps/identity/base
    kustomize:
      images:
        - alpine/k8s:1.30.13
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
